services:
  - type: web
    name: mebenmodel
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://mebenmodel_db_3rq8_user:Jz3tDZakhWRotovrcrkSMvfpxZRlLVpA@dpg-d7l6bdn7f7vs73as6dk0-a/mebenmodel_db_3rq8
